package mesosphere.marathon

import scala.Predef._

/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
  /** The value is "marathon". */
  val name: String = "marathon"
  /** The value is "1.5.0-test". */
  val version: String = "1.5.0-test"
  /** The value is "2.11.8". */
  val scalaVersion: String = "2.11.8"
  /** The value is "971ad6a38cb84e3408a78ec81d36c60393cb5079". */
  val buildref: String = "971ad6a38cb84e3408a78ec81d36c60393cb5079"
  override val toString: String = {
    "name: %s, version: %s, scalaVersion: %s, buildref: %s" format (
      name, version, scalaVersion, buildref
    )
  }
}
